const express = require('express');
// var cron = require('node-cron');
const axios = require('axios');
const schedule = require('node-schedule');
const router = express.Router();
const presignedUrl = require('../controllers/presigneUrl.js');
const reads3Datas = require('../controllers/reads3Data.js');
const s3Controller = require('../controllers/s3BucketActivity.js');
router.get('/presigned-url/:fileName', presignedUrl.presigneUrl);
router.get('/read-s3-data', s3Controller.reads3Data);
router.get('/read-s3-datas/:fileName', s3Controller.reads3Datas);
router.get('/get-presigned-url', s3Controller.presinedUrl);
router.post('/add-file', s3Controller.addFile);
router.get('/get-all-files', s3Controller.getAllFiles);
module.exports = router;
